// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyDuG9-wAq77ffbM2yVdDSH4tV3CL9QU62s'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:325399101677:web:a66f8cc55af4964934cce4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '325399101677'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'chatrx-ef365'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN',
        defaultValue: 'chatrx-ef365.firebaseapp.com'),
    databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'chatrx-ef365.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_MEASUREMENT_ID',
        defaultValue: 'G-YBWXBD2S2V'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY',
        defaultValue: 'AIzaSyCT5EiRapF2nwg_S5OwxhmwrR2r3CQZAXg'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:325399101677:android:5571a813f762252d34cce4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '325399101677'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'chatrx-ef365'),
    databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'chatrx-ef365.firebasestorage.app'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyCgqCtUi7T7PrQlwNMgiJpysIrdDZZGhvc'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:325399101677:ios:243503b5bab2e62434cce4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '325399101677'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'chatrx-ef365'),
    databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'chatrx-ef365.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.example.nextgenApp'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyCgqCtUi7T7PrQlwNMgiJpysIrdDZZGhvc'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:325399101677:ios:243503b5bab2e62434cce4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '325399101677'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'chatrx-ef365'),
    databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'chatrx-ef365.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.example.nextgenApp'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyDuG9-wAq77ffbM2yVdDSH4tV3CL9QU62s'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:325399101677:web:70f925ab3d0ad7c034cce4'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '325399101677'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'chatrx-ef365'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN',
        defaultValue: 'chatrx-ef365.firebaseapp.com'),
    databaseURL: String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'chatrx-ef365.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_MEASUREMENT_ID',
        defaultValue: 'G-P54TGJR2VH'),
  );
}
