// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuG9-wAq77ffbM2yVdDSH4tV3CL9QU62s',
    appId: '1:325399101677:web:a66f8cc55af4964934cce4',
    messagingSenderId: '325399101677',
    projectId: 'chatrx-ef365',
    authDomain: 'chatrx-ef365.firebaseapp.com',
    databaseURL:
        'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatrx-ef365.firebasestorage.app',
    measurementId: 'G-YBWXBD2S2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5EiRapF2nwg_S5OwxhmwrR2r3CQZAXg',
    appId: '1:325399101677:android:5571a813f762252d34cce4',
    messagingSenderId: '325399101677',
    projectId: 'chatrx-ef365',
    databaseURL:
        'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatrx-ef365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgqCtUi7T7PrQlwNMgiJpysIrdDZZGhvc',
    appId: '1:325399101677:ios:243503b5bab2e62434cce4',
    messagingSenderId: '325399101677',
    projectId: 'chatrx-ef365',
    databaseURL:
        'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatrx-ef365.firebasestorage.app',
    iosBundleId: 'com.example.nextgenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgqCtUi7T7PrQlwNMgiJpysIrdDZZGhvc',
    appId: '1:325399101677:ios:243503b5bab2e62434cce4',
    messagingSenderId: '325399101677',
    projectId: 'chatrx-ef365',
    databaseURL:
        'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatrx-ef365.firebasestorage.app',
    iosBundleId: 'com.example.nextgenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuG9-wAq77ffbM2yVdDSH4tV3CL9QU62s',
    appId: '1:325399101677:web:70f925ab3d0ad7c034cce4',
    messagingSenderId: '325399101677',
    projectId: 'chatrx-ef365',
    authDomain: 'chatrx-ef365.firebaseapp.com',
    databaseURL:
        'https://chatrx-ef365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatrx-ef365.firebasestorage.app',
    measurementId: 'G-P54TGJR2VH',
  );
}
